$font = SpaceMono Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
}

label {
    monitor =
    text = $TIME
    font_size = 88
    font_family = $font
    color = rgba(ffffffff)
    position = 0, 310
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 22
    font_family = $font
    color = rgba(ccffffff)
    position = 0, 200
    halign = center
    valign = center
}

# label {
#     monitor =
#     text = Type password to unlock
#     font_size = 16
#     font_family = $font
#     color = rgba(bfffffff)
#     position = 0, 72
#     halign = center
#     valign = center
# }

input-field {
    monitor =
    size = 28%, 4%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.35)
    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(00ccffee) 45deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(230, 230, 230)
    fade_on_empty = false
    rounding = 12
    font_family = $font
    placeholder_text = Password...
    fail_text = $PAMFAIL
    # dots_text_format = *
    dots_size = 0.33
    dots_spacing = 0.22

    position = 0, 0
    halign = center
    valign = center
}

# Bottom power bar
shape {
    monitor =
    size = 580, 60
    color = rgba(00000066)
    rounding = 12
    position = 0, 26
    halign = center
    valign = bottom
}

label {
    monitor =
    text = ⏻ Shutdown
    font_size = 18
    font_family = $font
    color = rgba(ffffffff)
    position = -190, 38
    halign = center
    valign = bottom
    onclick = systemctl poweroff
}

label {
    monitor =
    text =  Reboot
    font_size = 18
    font_family = $font
    color = rgba(ffffffff)
    position = 0, 38
    halign = center
    valign = bottom
    onclick = systemctl reboot
}

label {
    monitor =
    text = ⏾ Suspend
    font_size = 18
    font_family = $font
    color = rgba(ffffffff)
    position = 190, 38
    halign = center
    valign = bottom
    onclick = systemctl suspend
}
