#!/usr/bin/env zsh
alias tf='source ~/tensorflow/bin/activate'
alias fr='source ~/far-range/bin/activate'
alias tf2='source ~/tensorflow-2/bin/activate'
alias asenv='source ~/airsim/bin/activate'
alias -g ..='cd ..'
alias -g ...='cd ../..'
alias -g ....='cd ../../..'
alias matl='matlab -nodisplay'
alias unity3d='~/Unity-2018.2.2f1/Editor/Unity'
alias upd='sudo apt update'
alias upg='sudo apt -y upgrade'
# to make tmux display colors correctly
alias tmux="tmux" # -f $TMUX_CONFIG"
alias matlabq="matlab -nodesktop -nosplash"
alias gpureload="sudo rmmod nvidia_uvm ; sudo modprobe nvidia_uvm"
alias datacenter="/home/shared/Komodo\ Duo/data-center-linux-x86_64-v6.73-1/Data\ Center"
alias python="python3"
alias whoson="w -h|awk '{a[\$1]++} END{for(b in a) print b}'"
# if batcat is installed
if command -v batcat &> /dev/null; then
	alias bat="batcat"
fi
alias vim="nvim"
alias 'bash?'="bat $HOME/.cheatsheets/bash"
# alias fd="fdfind"

# suffix aliases
alias -s py=python3
alias -s rs=nvim
alias -s md=nvim
alias -s c=nvim
alias -s h=nvim
alias -s cpp=nvim
alias -s hpp=nvim
